const shortQuotes = [
	"You're a star student!",
	'You shine!',
	'You make me smile!',
	"I'm so proud of you!",
	'You are special!',
	'You are unique!',
	'I believe in you!',
	'You made my day!',
	'You are so helpful!',
	'You brighten my day!',
	'You have a great attitude!',
	'Keep up the good work!',
	"You're a shining star!",
	"You're so talented!",
	'You amaze me!',
	'You are incredible!',
	'You are so kind!',
	'You are so thoughtful!',
	'You are a joy to be around!',
	"You're #1!",
	'Give it a try!',
	'Go for it!',
	'Why not?',
	'It’s worth a shot!',
	'What are you waiting for?',
	'What do you have to lose?',
	'You might as well!',
	'Just do it!',
	'There you go!',
	'Keep up the good work!',
	'Keep it up!',
	'Good job!',
	'I’m so proud of you!',
	'Hang in there!',
	'Don’t give up!',
	'Keep pushing!',
	'Keep fighting!',
	'Stay strong!',
	'Never give up!',
	'Never say ‘die’!',
	'Come on! You can do it!',
	'I’ll support you either way!',
	'I’m behind you 100%!',
	'It’s totally up to you..',
	'It’s your call!',
	'Follow your dreams!',
	'Reach for the stars!',
	'Do the impossible!',
	'Believe in yourself!',
	'The sky is the limit!',
];
module.exports = shortQuotes;
